applications:
  - name: verify-service-provider-production
    memory: 1G
    routes:
      - route: verify-service-provider-production.apps.internal
    stack: cflinuxfs3
    buildpack: java_buildpack
    command: (cd verify-service-provider-* && bin/verify-service-provider server vsp-eidas-without-matching.yml )
    env:
      JAVA_HOME: "../.java-buildpack/open_jdk_jre"
      CLOCK_SKEW: PT30s
      VERIFY_ENVIRONMENT: PRODUCTION
      EUROPEAN_IDENTITY_ENABLED: true
      TRUSTSTORE_PASSWORD: puppet
